### ISSUE TITLE
StackHPC fork

### ISSUE THREAD

**Issue by markgoddard** [aruhier/ansible-role-systemd-networkd#6]
Hi, I wanted to let you know that I forked this role for use in one of our projects. I am open to contributing some or all of the changes back to your repository, but forked the role initially as I wanted the freedom to quickly change things. I expect there will be more changes at some point.

Here is the diff, I can open a PR if you are interested in any of this.

https://github.com/aruhier/ansible-role-systemd-networkd/compare/master...stackhpc:master

Thanks!
Mark

**Comment by aruhier** [comment]
Hi,
Yeah it sounds like a good idea! I reviewed the diff and I see nothing that I'm against on, and the file cleanup is a good addition.

Do a PR and I'll merge it.
